In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset=pd.read_csv('cars.csv')
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:, -1].values
print(X)
print(Y)

[['Toyota' 1000 790]
 ['Mitsubishi' 1200 1160]
 ['Suzuki' 1000 929]
 ['Suzuki' 900 865]
 ['Toyota' 1500 1140]
 ['Suzuki' 1000 929]
 ['Suzuki' 1400 1109]
 ['Honda' 1500 1365]
 ['Mazda' 1500 1112]
 ['Toyota' 1600 1150]
 ['Suzuki' 1100 980]
 ['Suzuki' 1300 990]
 ['Mazda' 1000 1112]
 ['Honda' 1600 1252]
 ['Suzuki' 1600 1326]
 ['Mitsubishi' 1600 1330]
 ['Mitsubishi' 1600 1365]
 ['Mazda' 2200 1280]
 ['Suzuki' 1600 1119]
 ['Mazda' 2000 1328]
 ['Mazda' 1600 1584]
 ['Mitsubishi' 2000 1428]
 ['Honda' 2100 1365]
 ['Suzuki' 1600 1415]
 ['Mazda' 2000 1415]
 ['Honda' 1500 1465]
 ['Toyota' 2000 1490]
 ['Toyota' 2000 1725]
 ['Mazda' 1600 1523]
 ['Mitsubishi' 2000 1705]
 ['Honda' 2100 1605]
 ['Mazda' 2000 1746]
 ['Mazda' 1600 1235]
 ['Mitsubishi' 1600 1390]
 ['Mitsubishi' 1600 1405]
 ['Honda' 2500 1395]]
[ 99  95  95  90 105 105  90  92  98  99  99 101  99  94  97  97  99 104
 104 105  94  99  99  99  99 102 104 114 109 114 115 117 104 108 109 120]


In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
CategoricalColumns=['Car','Model']
#Getting Dummy Pandas
# df= pd.get_dummies(dataset, columns=CategoricalColumns)
# ohe=OneHotEncoder()
# transformed_data= ohe.fit_transform(dataset[CategoricalColumns])
# encoded_data = pd.DataFrame(transformed_data, index=dataset.index)
# concatenated_data=pd.concat([dataset, encoded_data], axis=1)

ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
ct.fit_transform(X)
X=np.array(ct.fit_transform(X))
print(X)


[[0.0 0.0 0.0 0.0 1.0 1000 790]
 [0.0 0.0 1.0 0.0 0.0 1200 1160]
 [0.0 0.0 0.0 1.0 0.0 1000 929]
 [0.0 0.0 0.0 1.0 0.0 900 865]
 [0.0 0.0 0.0 0.0 1.0 1500 1140]
 [0.0 0.0 0.0 1.0 0.0 1000 929]
 [0.0 0.0 0.0 1.0 0.0 1400 1109]
 [1.0 0.0 0.0 0.0 0.0 1500 1365]
 [0.0 1.0 0.0 0.0 0.0 1500 1112]
 [0.0 0.0 0.0 0.0 1.0 1600 1150]
 [0.0 0.0 0.0 1.0 0.0 1100 980]
 [0.0 0.0 0.0 1.0 0.0 1300 990]
 [0.0 1.0 0.0 0.0 0.0 1000 1112]
 [1.0 0.0 0.0 0.0 0.0 1600 1252]
 [0.0 0.0 0.0 1.0 0.0 1600 1326]
 [0.0 0.0 1.0 0.0 0.0 1600 1330]
 [0.0 0.0 1.0 0.0 0.0 1600 1365]
 [0.0 1.0 0.0 0.0 0.0 2200 1280]
 [0.0 0.0 0.0 1.0 0.0 1600 1119]
 [0.0 1.0 0.0 0.0 0.0 2000 1328]
 [0.0 1.0 0.0 0.0 0.0 1600 1584]
 [0.0 0.0 1.0 0.0 0.0 2000 1428]
 [1.0 0.0 0.0 0.0 0.0 2100 1365]
 [0.0 0.0 0.0 1.0 0.0 1600 1415]
 [0.0 1.0 0.0 0.0 0.0 2000 1415]
 [1.0 0.0 0.0 0.0 0.0 1500 1465]
 [0.0 0.0 0.0 0.0 1.0 2000 1490]
 [0.0 0.0 0.0 0.0 1.0 2000 1725]
 [0.0 1.0 0.0 0.0 0.0 1600 1523]
 [0.0 0.0 1.0 0.0 0.0 2000 1705]
 [1.0 0.0 0.0 0.0

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=1)

In [6]:
print(X_train.shape)
print(Y_train)

(28, 7)
[114 104 114 108  99 102 105  95  97  99 104  99 117  94 104  90  94  92
 120  95  99  99  97 105 101  99  98  99]


In [7]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression()

In [8]:
Y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[105.08 115.  ]
 [102.64 109.  ]
 [102.09 109.  ]
 [ 93.72  90.  ]
 [106.14 105.  ]
 [108.31 104.  ]
 [107.32  99.  ]
 [103.37  99.  ]]


In [9]:
print(regressor.predict([[0,0,0,1,0,670,1000]]))

[91.46]
